In [44]:
from pathlib import Path
import pandas as pd

In [45]:
def crear_df(ruta):
    archivos = sorted(Path(ruta).glob("*.csv.zip"))
    df = pd.concat([pd.read_csv(a, index_col=0,) for a in archivos], ignore_index= True)
    return df

In [46]:
df = crear_df('../files/input')

In [47]:
df

,client_id,age,job,marital,education,credit_default,mortgage,month,day,contact_duration,number_contacts,previous_campaign_contacts,previous_outcome,cons_price_idx,euribor_three_months,campaign_outcome
0,0,56,housemaid,married,basic.4y,no,no,may,13,261,1,0,nonexistent,93.994,4.857,no
1,1,57,services,married,high.school,unknown,no,may,19,149,1,0,nonexistent,93.994,4.857,no
2,2,37,services,married,high.school,no,yes,may,23,226,1,0,nonexistent,93.994,4.857,no
3,3,40,admin.,married,basic.6y,no,no,may,27,151,1,0,nonexistent,93.994,4.857,no
4,4,56,services,married,high.school,no,no,may,3,307,1,0,nonexistent,93.994,4.857,no
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
41183,41183,73,retired,married,professional.course,no,yes,nov,30,334,1,0,nonexistent,94.767,1.028,yes
41184,41184,46,blue-collar,married,professional.course,no,no,nov,6,383,1,0,nonexistent,94.767,1.028,no
41185,41185,56,retired,married,university.degree,no,yes,nov,24,189,2,0,nonexistent,94.767,1.028,no
41186,41186,44,technician,married,professional.course,no,no,nov,17,442,1,0,nonexistent,94.767,1.028,yes
41187,41187,74,retired,married,professional.course,no,yes,nov,23,239,3,1,failure,94.767,1.028,no

In [48]:
def limpieza_df(df):

    df['job'] = df['job'].str.replace('.','',regex = False)
    df['job'] = df['job'].str.replace('-','_',regex = False)

    df['education'] = df['education'].str.replace('.','_',regex = False)
    df['education'] = df['education'].replace('unknown',pd.NA)

    df['credit_default'] = (df['credit_default'] == 'yes').astype(int)

    df['mortgage'] = (df['mortgage'] == 'yes').astype(int)

    df['previous_outcome'] = (df['previous_outcome'] == 'success').astype(int)

    df['campaign_outcome'] = (df['campaign_outcome'] == 'yes').astype(int)

    df['last_contact_date'] = '2022-' + df['month'] + '-' + df['day'].astype('str')
    df['last_contact_date'] =pd.to_datetime(df['last_contact_date'],format="%Y-%b-%d")
    df['last_contact_date'] = df['last_contact_date'].dt.strftime("%Y-%m-%d")

    return df

In [49]:
df_limpio = limpieza_df(df)

In [ ]:
columnas_client = [
    "client_id",
    "age",
    "job",
    "marital",
    "education",
    "credit_default",
    "mortgage",
]

columnas_campaign = [
    "client_id",
    "number_contacts",
    "contact_duration",
    "previous_campaign_contacts",
    "previous_outcome",
    "campaign_outcome",
    "last_contact_date",
]

columnas_economics = [
    "client_id",
    "cons_price_idx",
    "euribor_three_months",
]

In [52]:
clients = df[columnas_client]
campaigns = df[columnas_campaign]
economics = df[columnas_economics]

In [53]:
clients

,client_id,age,job,marital,education,credit_default,mortgage
0,0,56,housemaid,married,basic_4y,0,0
1,1,57,services,married,high_school,0,0
2,2,37,services,married,high_school,0,1
3,3,40,admin,married,basic_6y,0,0
4,4,56,services,married,high_school,0,0
...,...,...,...,...,...,...,...
41183,41183,73,retired,married,professional_course,0,1
41184,41184,46,blue_collar,married,professional_course,0,0
41185,41185,56,retired,married,university_degree,0,1
41186,41186,44,technician,married,professional_course,0,0
41187,41187,74,retired,married,professional_course,0,1

In [54]:
campaigns

,client_id,number_contacts,contact_duration,previous_campaign_contacts,previous_outcome,campaign_outcome,last_contact_date
0,0,1,261,0,0,0,2022-05-13
1,1,1,149,0,0,0,2022-05-19
2,2,1,226,0,0,0,2022-05-23
3,3,1,151,0,0,0,2022-05-27
4,4,1,307,0,0,0,2022-05-03
...,...,...,...,...,...,...,...
41183,41183,1,334,0,0,1,2022-11-30
41184,41184,1,383,0,0,0,2022-11-06
41185,41185,2,189,0,0,0,2022-11-24
41186,41186,1,442,0,0,1,2022-11-17
41187,41187,3,239,1,0,0,2022-11-23

In [55]:
economics

       client_id  cons_price_idx  euribor_three_months
0              0          93.994                 4.857
1              1          93.994                 4.857
2              2          93.994                 4.857
3              3          93.994                 4.857
4              4          93.994                 4.857
...          ...             ...                   ...
41183      41183          94.767                 1.028
41184      41184          94.767                 1.028
41185      41185          94.767                 1.028
41186      41186          94.767                 1.028
41187      41187          94.767                 1.028

[41188 rows x 3 columns]